baseURL = 'https://soktai.prose.sh/'
languageCode = 'en-ca'
title = "Soktai's FFXIV"
enableGitInfo = true

# Theme is intended for documentation use
disableKinds = ['taxonomy']

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[menu]
[[menu.after]]
name = 'Lodestone'
url = 'https://na.finalfantasyxiv.com/lodestone/'
weight = 20

[[menu.after]]
name = "FFXIV Console Game Wiki"
url = "https://ffxiv.consolegameswiki.com/wiki/FF14_Wiki"
weight = 30

[[menu.after]]
name = "Teamcraft"
url = "https://ffxivteamcraft.com/"
weight = 40

[[menu.after]]
name = "Garland Tools"
url = "https://www.garlandtools.org/db/"
weight = 50

[[menu.after]]

[params]
BookTheme = "auto"
BookSection = "*"
BookDateFormat = '2006-01-02'
BookComments = false
BookRepo = 'https://github.com/tx0dev/ffxiv'
BookCommitPath = 'commit'
BookEditPath = 'edit/main'
BookSearch = true
